Add missing import needed for `token='cloud'`
Currently using `token='cloud'` gives the following error:
```
GCSFileSystem(project='blah', token='cloud')
...
~/miniconda3/lib/python3.6/site-packages/gcsfs/core.py in _connect_cloud(self)
    235
    236     def _connect_cloud(self):
--> 237         credentials = gauth.compute_engine.Credentials()
    238         self.session = AuthorizedSession(credentials)
    239

AttributeError: module 'google.auth' has no attribute 'compute_engine'
```

Adding the explicit `compute_engine` import fixes this.